version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm i --no-optional
      - npm install serverless -g
  build:
    commands:
      - serverless deploy
  post_build:
    commands: echo 'done'